-- ---- Blocks for 1.1 -----

INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (0, 'Air');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (1, 'Stone'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (2, 'Grass Block');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (3, 'Dirt');  
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (4, 'Cobblestone'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (5, 'Wooden Planks'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (6, 'Saplings');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (7, 'Bedrock');  
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (8, 'Water');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (9, 'Stationary Water');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (10, 'Lava');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (11, 'Stationary Water');    
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (12, 'Sand'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (13, 'Gravel'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (14, 'Gold Ore'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (15, 'Iron Ore'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (16, 'Coal Ore'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (17, 'Wood'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (18, 'Leaves'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (19, 'Sponge'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (20, 'Glass'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (21, 'Lapis Lazuli Ore'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (22, 'Lapis Lazuli Block'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (23, 'Dispenser'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (24, 'Sandstone'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (25, 'Note Block'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (26, 'Bed'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (27, 'Powered Rail'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (28, 'Detector Rail'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (29, 'Sticky Piston');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (30, 'Cobweb');  
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (31, 'Tall Grass'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (32, 'Dead Bush'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (33, 'Piston'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (34, 'Piston Extension'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (35, 'Wool'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (36, 'Piston moved Block'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (37, 'Dandelion'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (38, 'Rose'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (39, 'Brown Mushroom'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (40, 'Red Mushroom'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (41, 'Gold Block'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (42, 'Iron Block'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (43, 'Double Slabs'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (44, 'Slabs');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (45, 'Bricks');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (46, 'TNT');   
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (47, 'Bookshelf'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (48, 'Moss Stone'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (49, 'Obsidian'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (50, 'Torch'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (51, 'Fire'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (52, 'Monster Spawner'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (53, 'Wooden Stairs');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (54, 'Chest');  
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (55, 'Redstone Wire'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (56, 'Diamond Ore'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (57, 'Diamond Block'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (58, 'Crafting Table'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (59, 'Wheat Seeds'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (60, 'Farmland');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (61, 'Furnace');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (62, 'Burning Furnace'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (63, 'Post Sign');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (64, 'Wooden Door');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (65, 'Ladders');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (66, 'Rails');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (67, 'Cobblestone Stairs'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (68, 'Wall Sign'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (69, 'Lever'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (70, 'Stone Pressure Plate'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (71, 'Iron Door'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (72, 'Wooden Pressure Plate'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (73, 'Redstone Ore');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (74, 'Glowing Redstone Ore'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (75, 'Redstone Torch (off)');  
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (76, 'Redstone Torch (on)'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (77, 'Stone Button'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (78, 'Snow'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (79, 'Ice'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (80, 'Snow Block'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (81, 'Cactus'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (82, 'Clay Block'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (83, 'Sugar Cane'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (84, 'Jukebox');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (85, 'Fence');  
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (86, 'Pumpkin'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (87, 'Netherrack'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (88, 'Soul Sand'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (89, 'Glowstone Block'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (90, 'Portal'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (91, 'Jack-O-Latern'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (92, 'Cake Block'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (93, 'Redstone Repeater (off)'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (94, 'Redstone Repeater (off)'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (95, 'Locked Chest');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (96, 'Trapdoor');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (97, 'Hidden Silverfish'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (98, 'Stone Bricks'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (99, 'Huge Brown Mushroom'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (100, 'Huge Red Mushroom'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (101, 'Iron Bars'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (102, 'Glass Pane'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (103, 'Melon'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (104, 'Pumpkin Stem'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (105, 'Melon Stem'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (106, 'Vines'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (107, 'Fence Gate'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (108, 'Brick Stairs'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (109, 'Stone Brick Stairs'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (110, 'Mycelium');
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (111, 'Lily Pad');  
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (112, 'Nether Brick'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (113, 'Nether Brick Fence'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (114, 'Nether Brick Stairs'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (115, 'Nether Wart'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (116, 'Enchantment Table'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (117, 'Brewing Stand'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (118, 'Cauldron'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (119, 'End Portal'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (120, 'End Portal Frame'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (121, 'End Stone'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (122, 'Dragon Egg'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (123, 'Redstone Lamp (off)'); 
INSERT INTO "prefix_blocks" ("blockID", "name") VALUES (124, 'Redstone Lamp (on)'); 