-- ---- Items for 1.1 -----

INSERT INTO "prefix_items" ("itemID", "name") VALUES (256, 'Iron Shovel');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (257, 'Iron Pickaxe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (258, 'Iron Axe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (259, 'Flint and Steel');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (260, 'Red Apple');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (261, 'Bow');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (262, 'Arrpw');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (263, 'Coal');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (264, 'Diamond');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (265, 'Iron Ingot');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (266, 'Gold Ingot');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (267, 'Iron Sword');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (268, 'Wooden Sword');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (269, 'Wooden Shovel');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (270, 'Wooden Pickaxe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (271, 'Wooden Axe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (272, 'Stone Sword');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (273, 'Stone Shovel');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (274, 'Stone Pickaxe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (275, 'Stone Axe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (276, 'Diamond Sword');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (277, 'Diamond Shovel');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (278, 'Diamond Pickaxe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (279, 'Diamond Axe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (280, 'Stick');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (281, 'Bowl');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (282, 'Mushroom Soup');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (283, 'Gold Sword');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (284, 'Gold Shovel');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (285, 'Gold Pickaxe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (286, 'Gold Axe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (287, 'String');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (288, 'Feather');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (289, 'Gunpowder');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (290, 'Wooden Hoe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (291, 'Stone Hoe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (292, 'Iron Hoe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (293, 'Diamond Hoe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (294, 'Gold Hoe');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (295, 'Seeds');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (296, 'Wheat');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (297, 'Bread');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (298, 'Leather Cap');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (299, 'Leather Tunic');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (300, 'Leahter Pants');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (301, 'Leather Boots');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (302, 'Chain Helmet');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (303, 'Chain Chestplate');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (304, 'Chain Leggings');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (305, 'Chain Boots');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (306, 'Iron Helmet');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (307, 'Iron Chestplate');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (308, 'Iron Leggings');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (309, 'Iron Boots');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (310, 'Diamond Helmet');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (311, 'Diamond Chestplate');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (312, 'Diamond Leggings');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (313, 'Diamond Boots');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (314, 'Gold Helmet');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (315, 'Gold Chestplate');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (316, 'Gold Leggings');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (317, 'Gold Boots');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (318, 'Flint');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (319, 'Raw Porkchop');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (320, 'Cooked Porkchop');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (321, 'Paintings');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (322, 'Golden Apple');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (323, 'Sign');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (324, 'Wooden Door');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (325, 'Bucket');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (326, 'Water Bucket');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (327, 'Lava Bucket');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (328, 'Minecart');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (329, 'Saddle');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (330, 'Iron Door');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (331, 'Redstone');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (332, 'Snowball');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (333, 'Boat');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (334, 'Leather');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (335, 'Milk');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (336, 'Clay Brick');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (337, 'Clay');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (338, 'Sugar Cane');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (339, 'Paper');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (340, 'Boock');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (341, 'Slime Ball');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (342, 'Minecart with Chest');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (343, 'Minecart with Furnace');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (344, 'Chicken Egg');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (345, 'Compass');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (346, 'Fishing Rod');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (347, 'Clock');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (348, 'Glowstone Dust');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (349, 'Raw Fish');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (350, 'Cooked Fish');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (351, 'Dye');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (352, 'Bone');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (353, 'Sugar');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (354, 'Cake');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (355, 'Bed');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (356, 'Redstone Repeater');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (357, 'Cookie');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (358, 'Map');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (359, 'Shears');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (360, 'Melon Slice');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (361, 'Pumpkin Seeds');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (362, 'Melon Seeds');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (363, 'Raw Beef');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (364, 'Steak');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (365, 'Raw Chicken');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (366, 'Cooked Chicken');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (367, 'Rotten Flesh');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (368, 'Ender Pearl');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (369, 'Blate Rod');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (370, 'Ghast Tear');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (371, 'Gold Nugget');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (372, 'Neather Wart');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (373, 'Potions');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (374, 'Glass Bottle');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (375, 'Spider Eye');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (376, 'Fermented Spider Eye');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (377, 'Blaze Powder');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (378, 'Magma Crean');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (379, 'Brewing Stand');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (380, 'Cauldron');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (381, 'Eye of Ender');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (382, 'Glistering Melon');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (383, 'Spawn Egg');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (384, 'Bottle o\' Enchanting');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (385, 'Fire Charge');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2256, '13 Disc');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2257, 'Cat Disc');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2258, 'blocks Disc');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2259, 'chirp Disc');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2260, 'far Disc');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2261, 'mall Disc');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2262, 'mellohi Disc');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2263, 'stal Disc');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2264, 'strad Disc');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2265, 'ward Disc');
INSERT INTO "prefix_items" ("itemID", "name") VALUES (2266, '11 Disc');